# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_env: &default_env
  # S3 Configuration
  S3_KEY: 'AKIAJV6GJWO7ZSR4VXGQ'
  S3_SECRET: 'itHJsqYTD9Xcn2OuWo+YnRkRrHMUYn6yyNzLHGuL'
  S3_BUCKET_NAME: 'selffer'
  S3_REGION: 'us-east-1'
  API_URL: "http://ec2-54-229-69-117.eu-west-1.compute.amazonaws.com"
  API_URL_EB: "http://selffer-api-dev.eu-west-1.elasticbeanstalk.com/api"
  TWILIO_ACCOUNT: "AC02e965185109a134413c5605c2288a90"
  TWILIO_AUTH: "8a33c9d4fd8d00bab7e4af0cf1254665"
  PHOTOGRAPHER_LOGO_HEIGHT: 50
  END_CLIENT_URL: 'localhost:3000'
  #url for sync data

development:
  env:
    <<: *default_env
    MAIN_SERVER_URL: 'http://localhost:3000'
  secret_key_base: 1743c3f6aab28e8f417513576813fa3107ea75b6d020602353cbccfe101ffb73a6e91abc3b02eb78646a7121dce9278da8170eca0744f3ee7ff0babca28ae690


test:
  secret_key_base: 223f75f6216529ae12c4cd51a49333bab8458adb094c19c1b782525c6ac760b23dbff4507bbafd1de3ee52bee34b8fb306d390d7a59a224d61f53922a737c3b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  env:
    <<: *default_env
    MAIN_SERVER_URL: 'http://www.selffer.com'
    API_URL: "http://ec2-52-17-174-148.eu-west-1.compute.amazonaws.com"
    API_URL_EB: "http://selffer-api-dev.eu-west-1.elasticbeanstalk.com/api"
